# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild

SHELLTYPE := posix
ifeq ($(shell echo "test"), "test")
	SHELLTYPE := msdos
endif

# Configurations
# #############################################

ifeq ($(origin CC), default)
  CC = gcc
endif
ifeq ($(origin CXX), default)
  CXX = g++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
RESCOMP = windres
INCLUDES += -I.
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LIBS +=
LDDEPS +=
LINKCMD = $(AR) -rcs "$@" $(OBJECTS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef
define POSTBUILDCMDS
endef

ifeq ($(config),debug_x64)
TARGETDIR = bin/Debug-linux-x86_64/Jolt
TARGET = $(TARGETDIR)/libJolt.a
OBJDIR = bin-int/Debug-linux-x86_64/Jolt
DEFINES += -DJPH_CROSS_PLATFORM_DETERMINISTIC -DJPH_DEBUG_RENDERER -DDEBUG -D_DEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -g -Wall -Wextra -std=c++17
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64

else ifeq ($(config),release_x64)
TARGETDIR = bin/Release-linux-x86_64/Jolt
TARGET = $(TARGETDIR)/libJolt.a
OBJDIR = bin-int/Release-linux-x86_64/Jolt
DEFINES += -DJPH_CROSS_PLATFORM_DETERMINISTIC -DJPH_DEBUG_RENDERER -DNDEBUG
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -O3 -mavx2 -Wall -Wextra -ffast-math
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -O3 -mavx2 -Wall -Wextra -std=c++17 -ffast-math
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -s -flto

else ifeq ($(config),dist_x64)
TARGETDIR = bin/Dist-linux-x86_64/Jolt
TARGET = $(TARGETDIR)/libJolt.a
OBJDIR = bin-int/Dist-linux-x86_64/Jolt
DEFINES += -DJPH_CROSS_PLATFORM_DETERMINISTIC -DJPH_DEBUG_RENDERER
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -O3 -mavx2 -Wall -Wextra -ffast-math
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -O3 -mavx2 -Wall -Wextra -std=c++17 -ffast-math
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -s -flto

endif

# Per File Configurations
# #############################################


# File sets
# #############################################

GENERATED :=
OBJECTS :=

GENERATED += $(OBJDIR)/AABBTreeBuilder.o
GENERATED += $(OBJDIR)/Body.o
GENERATED += $(OBJDIR)/BodyCreationSettings.o
GENERATED += $(OBJDIR)/BodyInterface.o
GENERATED += $(OBJDIR)/BodyManager.o
GENERATED += $(OBJDIR)/BoxShape.o
GENERATED += $(OBJDIR)/BroadPhase.o
GENERATED += $(OBJDIR)/BroadPhaseBruteForce.o
GENERATED += $(OBJDIR)/BroadPhaseQuadTree.o
GENERATED += $(OBJDIR)/CapsuleShape.o
GENERATED += $(OBJDIR)/CastConvexVsTriangles.o
GENERATED += $(OBJDIR)/CastSphereVsTriangles.o
GENERATED += $(OBJDIR)/Character.o
GENERATED += $(OBJDIR)/CharacterBase.o
GENERATED += $(OBJDIR)/CharacterVirtual.o
GENERATED += $(OBJDIR)/CollideConvexVsTriangles.o
GENERATED += $(OBJDIR)/CollideSphereVsTriangles.o
GENERATED += $(OBJDIR)/CollisionDispatch.o
GENERATED += $(OBJDIR)/CollisionGroup.o
GENERATED += $(OBJDIR)/Color.o
GENERATED += $(OBJDIR)/CompoundShape.o
GENERATED += $(OBJDIR)/ConeConstraint.o
GENERATED += $(OBJDIR)/Constraint.o
GENERATED += $(OBJDIR)/ConstraintManager.o
GENERATED += $(OBJDIR)/ContactConstraintManager.o
GENERATED += $(OBJDIR)/ConvexHullBuilder.o
GENERATED += $(OBJDIR)/ConvexHullBuilder2D.o
GENERATED += $(OBJDIR)/ConvexHullShape.o
GENERATED += $(OBJDIR)/ConvexShape.o
GENERATED += $(OBJDIR)/CylinderShape.o
GENERATED += $(OBJDIR)/DebugRenderer.o
GENERATED += $(OBJDIR)/DebugRendererPlayback.o
GENERATED += $(OBJDIR)/DebugRendererRecorder.o
GENERATED += $(OBJDIR)/DebugRendererSimple.o
GENERATED += $(OBJDIR)/DecoratedShape.o
GENERATED += $(OBJDIR)/DeterminismLog.o
GENERATED += $(OBJDIR)/DistanceConstraint.o
GENERATED += $(OBJDIR)/EmptyShape.o
GENERATED += $(OBJDIR)/EstimateCollisionResponse.o
GENERATED += $(OBJDIR)/Factory.o
GENERATED += $(OBJDIR)/FixedConstraint.o
GENERATED += $(OBJDIR)/GearConstraint.o
GENERATED += $(OBJDIR)/GroupFilter.o
GENERATED += $(OBJDIR)/GroupFilterTable.o
GENERATED += $(OBJDIR)/HeightFieldShape.o
GENERATED += $(OBJDIR)/HingeConstraint.o
GENERATED += $(OBJDIR)/Indexify.o
GENERATED += $(OBJDIR)/IslandBuilder.o
GENERATED += $(OBJDIR)/IssueReporting.o
GENERATED += $(OBJDIR)/JobSystemSingleThreaded.o
GENERATED += $(OBJDIR)/JobSystemThreadPool.o
GENERATED += $(OBJDIR)/JobSystemWithBarrier.o
GENERATED += $(OBJDIR)/LargeIslandSplitter.o
GENERATED += $(OBJDIR)/LinearCurve.o
GENERATED += $(OBJDIR)/ManifoldBetweenTwoFaces.o
GENERATED += $(OBJDIR)/MassProperties.o
GENERATED += $(OBJDIR)/Memory.o
GENERATED += $(OBJDIR)/MeshShape.o
GENERATED += $(OBJDIR)/MotionProperties.o
GENERATED += $(OBJDIR)/MotorSettings.o
GENERATED += $(OBJDIR)/MotorcycleController.o
GENERATED += $(OBJDIR)/MutableCompoundShape.o
GENERATED += $(OBJDIR)/NarrowPhaseQuery.o
GENERATED += $(OBJDIR)/NarrowPhaseStats.o
GENERATED += $(OBJDIR)/ObjectStream.o
GENERATED += $(OBJDIR)/ObjectStreamBinaryIn.o
GENERATED += $(OBJDIR)/ObjectStreamBinaryOut.o
GENERATED += $(OBJDIR)/ObjectStreamIn.o
GENERATED += $(OBJDIR)/ObjectStreamOut.o
GENERATED += $(OBJDIR)/ObjectStreamTextIn.o
GENERATED += $(OBJDIR)/ObjectStreamTextOut.o
GENERATED += $(OBJDIR)/OffsetCenterOfMassShape.o
GENERATED += $(OBJDIR)/OrientedBox.o
GENERATED += $(OBJDIR)/PathConstraint.o
GENERATED += $(OBJDIR)/PathConstraintPath.o
GENERATED += $(OBJDIR)/PathConstraintPathHermite.o
GENERATED += $(OBJDIR)/PhysicsMaterial.o
GENERATED += $(OBJDIR)/PhysicsMaterialSimple.o
GENERATED += $(OBJDIR)/PhysicsScene.o
GENERATED += $(OBJDIR)/PhysicsSystem.o
GENERATED += $(OBJDIR)/PhysicsUpdateContext.o
GENERATED += $(OBJDIR)/PlaneShape.o
GENERATED += $(OBJDIR)/PointConstraint.o
GENERATED += $(OBJDIR)/Profiler.o
GENERATED += $(OBJDIR)/PulleyConstraint.o
GENERATED += $(OBJDIR)/QuadTree.o
GENERATED += $(OBJDIR)/RTTI.o
GENERATED += $(OBJDIR)/RackAndPinionConstraint.o
GENERATED += $(OBJDIR)/Ragdoll.o
GENERATED += $(OBJDIR)/RegisterTypes.o
GENERATED += $(OBJDIR)/RotatedTranslatedShape.o
GENERATED += $(OBJDIR)/ScaledShape.o
GENERATED += $(OBJDIR)/Semaphore.o
GENERATED += $(OBJDIR)/SerializableObject.o
GENERATED += $(OBJDIR)/Shape.o
GENERATED += $(OBJDIR)/SixDOFConstraint.o
GENERATED += $(OBJDIR)/SkeletalAnimation.o
GENERATED += $(OBJDIR)/Skeleton.o
GENERATED += $(OBJDIR)/SkeletonMapper.o
GENERATED += $(OBJDIR)/SkeletonPose.o
GENERATED += $(OBJDIR)/SliderConstraint.o
GENERATED += $(OBJDIR)/SoftBodyCreationSettings.o
GENERATED += $(OBJDIR)/SoftBodyMotionProperties.o
GENERATED += $(OBJDIR)/SoftBodyShape.o
GENERATED += $(OBJDIR)/SoftBodySharedSettings.o
GENERATED += $(OBJDIR)/SphereShape.o
GENERATED += $(OBJDIR)/SpringSettings.o
GENERATED += $(OBJDIR)/StateRecorderImpl.o
GENERATED += $(OBJDIR)/StaticCompoundShape.o
GENERATED += $(OBJDIR)/StringTools.o
GENERATED += $(OBJDIR)/SwingTwistConstraint.o
GENERATED += $(OBJDIR)/TaperedCapsuleShape.o
GENERATED += $(OBJDIR)/TaperedCylinderShape.o
GENERATED += $(OBJDIR)/TickCounter.o
GENERATED += $(OBJDIR)/TrackedVehicleController.o
GENERATED += $(OBJDIR)/TransformedShape.o
GENERATED += $(OBJDIR)/TriangleShape.o
GENERATED += $(OBJDIR)/TriangleSplitter.o
GENERATED += $(OBJDIR)/TriangleSplitterBinning.o
GENERATED += $(OBJDIR)/TriangleSplitterMean.o
GENERATED += $(OBJDIR)/TwoBodyConstraint.o
GENERATED += $(OBJDIR)/TypeDeclarations.o
GENERATED += $(OBJDIR)/Vec3.o
GENERATED += $(OBJDIR)/VehicleAntiRollBar.o
GENERATED += $(OBJDIR)/VehicleCollisionTester.o
GENERATED += $(OBJDIR)/VehicleConstraint.o
GENERATED += $(OBJDIR)/VehicleController.o
GENERATED += $(OBJDIR)/VehicleDifferential.o
GENERATED += $(OBJDIR)/VehicleEngine.o
GENERATED += $(OBJDIR)/VehicleTrack.o
GENERATED += $(OBJDIR)/VehicleTransmission.o
GENERATED += $(OBJDIR)/Wheel.o
GENERATED += $(OBJDIR)/WheeledVehicleController.o
OBJECTS += $(OBJDIR)/AABBTreeBuilder.o
OBJECTS += $(OBJDIR)/Body.o
OBJECTS += $(OBJDIR)/BodyCreationSettings.o
OBJECTS += $(OBJDIR)/BodyInterface.o
OBJECTS += $(OBJDIR)/BodyManager.o
OBJECTS += $(OBJDIR)/BoxShape.o
OBJECTS += $(OBJDIR)/BroadPhase.o
OBJECTS += $(OBJDIR)/BroadPhaseBruteForce.o
OBJECTS += $(OBJDIR)/BroadPhaseQuadTree.o
OBJECTS += $(OBJDIR)/CapsuleShape.o
OBJECTS += $(OBJDIR)/CastConvexVsTriangles.o
OBJECTS += $(OBJDIR)/CastSphereVsTriangles.o
OBJECTS += $(OBJDIR)/Character.o
OBJECTS += $(OBJDIR)/CharacterBase.o
OBJECTS += $(OBJDIR)/CharacterVirtual.o
OBJECTS += $(OBJDIR)/CollideConvexVsTriangles.o
OBJECTS += $(OBJDIR)/CollideSphereVsTriangles.o
OBJECTS += $(OBJDIR)/CollisionDispatch.o
OBJECTS += $(OBJDIR)/CollisionGroup.o
OBJECTS += $(OBJDIR)/Color.o
OBJECTS += $(OBJDIR)/CompoundShape.o
OBJECTS += $(OBJDIR)/ConeConstraint.o
OBJECTS += $(OBJDIR)/Constraint.o
OBJECTS += $(OBJDIR)/ConstraintManager.o
OBJECTS += $(OBJDIR)/ContactConstraintManager.o
OBJECTS += $(OBJDIR)/ConvexHullBuilder.o
OBJECTS += $(OBJDIR)/ConvexHullBuilder2D.o
OBJECTS += $(OBJDIR)/ConvexHullShape.o
OBJECTS += $(OBJDIR)/ConvexShape.o
OBJECTS += $(OBJDIR)/CylinderShape.o
OBJECTS += $(OBJDIR)/DebugRenderer.o
OBJECTS += $(OBJDIR)/DebugRendererPlayback.o
OBJECTS += $(OBJDIR)/DebugRendererRecorder.o
OBJECTS += $(OBJDIR)/DebugRendererSimple.o
OBJECTS += $(OBJDIR)/DecoratedShape.o
OBJECTS += $(OBJDIR)/DeterminismLog.o
OBJECTS += $(OBJDIR)/DistanceConstraint.o
OBJECTS += $(OBJDIR)/EmptyShape.o
OBJECTS += $(OBJDIR)/EstimateCollisionResponse.o
OBJECTS += $(OBJDIR)/Factory.o
OBJECTS += $(OBJDIR)/FixedConstraint.o
OBJECTS += $(OBJDIR)/GearConstraint.o
OBJECTS += $(OBJDIR)/GroupFilter.o
OBJECTS += $(OBJDIR)/GroupFilterTable.o
OBJECTS += $(OBJDIR)/HeightFieldShape.o
OBJECTS += $(OBJDIR)/HingeConstraint.o
OBJECTS += $(OBJDIR)/Indexify.o
OBJECTS += $(OBJDIR)/IslandBuilder.o
OBJECTS += $(OBJDIR)/IssueReporting.o
OBJECTS += $(OBJDIR)/JobSystemSingleThreaded.o
OBJECTS += $(OBJDIR)/JobSystemThreadPool.o
OBJECTS += $(OBJDIR)/JobSystemWithBarrier.o
OBJECTS += $(OBJDIR)/LargeIslandSplitter.o
OBJECTS += $(OBJDIR)/LinearCurve.o
OBJECTS += $(OBJDIR)/ManifoldBetweenTwoFaces.o
OBJECTS += $(OBJDIR)/MassProperties.o
OBJECTS += $(OBJDIR)/Memory.o
OBJECTS += $(OBJDIR)/MeshShape.o
OBJECTS += $(OBJDIR)/MotionProperties.o
OBJECTS += $(OBJDIR)/MotorSettings.o
OBJECTS += $(OBJDIR)/MotorcycleController.o
OBJECTS += $(OBJDIR)/MutableCompoundShape.o
OBJECTS += $(OBJDIR)/NarrowPhaseQuery.o
OBJECTS += $(OBJDIR)/NarrowPhaseStats.o
OBJECTS += $(OBJDIR)/ObjectStream.o
OBJECTS += $(OBJDIR)/ObjectStreamBinaryIn.o
OBJECTS += $(OBJDIR)/ObjectStreamBinaryOut.o
OBJECTS += $(OBJDIR)/ObjectStreamIn.o
OBJECTS += $(OBJDIR)/ObjectStreamOut.o
OBJECTS += $(OBJDIR)/ObjectStreamTextIn.o
OBJECTS += $(OBJDIR)/ObjectStreamTextOut.o
OBJECTS += $(OBJDIR)/OffsetCenterOfMassShape.o
OBJECTS += $(OBJDIR)/OrientedBox.o
OBJECTS += $(OBJDIR)/PathConstraint.o
OBJECTS += $(OBJDIR)/PathConstraintPath.o
OBJECTS += $(OBJDIR)/PathConstraintPathHermite.o
OBJECTS += $(OBJDIR)/PhysicsMaterial.o
OBJECTS += $(OBJDIR)/PhysicsMaterialSimple.o
OBJECTS += $(OBJDIR)/PhysicsScene.o
OBJECTS += $(OBJDIR)/PhysicsSystem.o
OBJECTS += $(OBJDIR)/PhysicsUpdateContext.o
OBJECTS += $(OBJDIR)/PlaneShape.o
OBJECTS += $(OBJDIR)/PointConstraint.o
OBJECTS += $(OBJDIR)/Profiler.o
OBJECTS += $(OBJDIR)/PulleyConstraint.o
OBJECTS += $(OBJDIR)/QuadTree.o
OBJECTS += $(OBJDIR)/RTTI.o
OBJECTS += $(OBJDIR)/RackAndPinionConstraint.o
OBJECTS += $(OBJDIR)/Ragdoll.o
OBJECTS += $(OBJDIR)/RegisterTypes.o
OBJECTS += $(OBJDIR)/RotatedTranslatedShape.o
OBJECTS += $(OBJDIR)/ScaledShape.o
OBJECTS += $(OBJDIR)/Semaphore.o
OBJECTS += $(OBJDIR)/SerializableObject.o
OBJECTS += $(OBJDIR)/Shape.o
OBJECTS += $(OBJDIR)/SixDOFConstraint.o
OBJECTS += $(OBJDIR)/SkeletalAnimation.o
OBJECTS += $(OBJDIR)/Skeleton.o
OBJECTS += $(OBJDIR)/SkeletonMapper.o
OBJECTS += $(OBJDIR)/SkeletonPose.o
OBJECTS += $(OBJDIR)/SliderConstraint.o
OBJECTS += $(OBJDIR)/SoftBodyCreationSettings.o
OBJECTS += $(OBJDIR)/SoftBodyMotionProperties.o
OBJECTS += $(OBJDIR)/SoftBodyShape.o
OBJECTS += $(OBJDIR)/SoftBodySharedSettings.o
OBJECTS += $(OBJDIR)/SphereShape.o
OBJECTS += $(OBJDIR)/SpringSettings.o
OBJECTS += $(OBJDIR)/StateRecorderImpl.o
OBJECTS += $(OBJDIR)/StaticCompoundShape.o
OBJECTS += $(OBJDIR)/StringTools.o
OBJECTS += $(OBJDIR)/SwingTwistConstraint.o
OBJECTS += $(OBJDIR)/TaperedCapsuleShape.o
OBJECTS += $(OBJDIR)/TaperedCylinderShape.o
OBJECTS += $(OBJDIR)/TickCounter.o
OBJECTS += $(OBJDIR)/TrackedVehicleController.o
OBJECTS += $(OBJDIR)/TransformedShape.o
OBJECTS += $(OBJDIR)/TriangleShape.o
OBJECTS += $(OBJDIR)/TriangleSplitter.o
OBJECTS += $(OBJDIR)/TriangleSplitterBinning.o
OBJECTS += $(OBJDIR)/TriangleSplitterMean.o
OBJECTS += $(OBJDIR)/TwoBodyConstraint.o
OBJECTS += $(OBJDIR)/TypeDeclarations.o
OBJECTS += $(OBJDIR)/Vec3.o
OBJECTS += $(OBJDIR)/VehicleAntiRollBar.o
OBJECTS += $(OBJDIR)/VehicleCollisionTester.o
OBJECTS += $(OBJDIR)/VehicleConstraint.o
OBJECTS += $(OBJDIR)/VehicleController.o
OBJECTS += $(OBJDIR)/VehicleDifferential.o
OBJECTS += $(OBJDIR)/VehicleEngine.o
OBJECTS += $(OBJDIR)/VehicleTrack.o
OBJECTS += $(OBJDIR)/VehicleTransmission.o
OBJECTS += $(OBJDIR)/Wheel.o
OBJECTS += $(OBJDIR)/WheeledVehicleController.o

# Rules
# #############################################

all: $(TARGET)
	@:

$(TARGET): $(GENERATED) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	$(PRELINKCMDS)
	@echo Linking Jolt
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Jolt
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(GENERATED)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) $(foreach f,$(subst /,\\,$(GENERATED)),if exist $(f) del /s /q $(f) >nul &)
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild: | $(OBJDIR)
	$(PREBUILDCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) | $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | prebuild
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) touch "$@"
else
	$(SILENT) echo $null >> "$@"
endif
else
$(OBJECTS): | prebuild
endif


# File Rules
# #############################################

$(OBJDIR)/AABBTreeBuilder.o: Jolt/AABBTree/AABBTreeBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Color.o: Jolt/Core/Color.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Factory.o: Jolt/Core/Factory.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IssueReporting.o: Jolt/Core/IssueReporting.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JobSystemSingleThreaded.o: Jolt/Core/JobSystemSingleThreaded.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JobSystemThreadPool.o: Jolt/Core/JobSystemThreadPool.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/JobSystemWithBarrier.o: Jolt/Core/JobSystemWithBarrier.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LinearCurve.o: Jolt/Core/LinearCurve.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Memory.o: Jolt/Core/Memory.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Profiler.o: Jolt/Core/Profiler.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RTTI.o: Jolt/Core/RTTI.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Semaphore.o: Jolt/Core/Semaphore.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StringTools.o: Jolt/Core/StringTools.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TickCounter.o: Jolt/Core/TickCounter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ConvexHullBuilder.o: Jolt/Geometry/ConvexHullBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ConvexHullBuilder2D.o: Jolt/Geometry/ConvexHullBuilder2D.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Indexify.o: Jolt/Geometry/Indexify.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/OrientedBox.o: Jolt/Geometry/OrientedBox.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Vec3.o: Jolt/Math/Vec3.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ObjectStream.o: Jolt/ObjectStream/ObjectStream.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ObjectStreamBinaryIn.o: Jolt/ObjectStream/ObjectStreamBinaryIn.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ObjectStreamBinaryOut.o: Jolt/ObjectStream/ObjectStreamBinaryOut.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ObjectStreamIn.o: Jolt/ObjectStream/ObjectStreamIn.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ObjectStreamOut.o: Jolt/ObjectStream/ObjectStreamOut.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ObjectStreamTextIn.o: Jolt/ObjectStream/ObjectStreamTextIn.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ObjectStreamTextOut.o: Jolt/ObjectStream/ObjectStreamTextOut.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SerializableObject.o: Jolt/ObjectStream/SerializableObject.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TypeDeclarations.o: Jolt/ObjectStream/TypeDeclarations.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Body.o: Jolt/Physics/Body/Body.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BodyCreationSettings.o: Jolt/Physics/Body/BodyCreationSettings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BodyInterface.o: Jolt/Physics/Body/BodyInterface.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BodyManager.o: Jolt/Physics/Body/BodyManager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MassProperties.o: Jolt/Physics/Body/MassProperties.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MotionProperties.o: Jolt/Physics/Body/MotionProperties.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Character.o: Jolt/Physics/Character/Character.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CharacterBase.o: Jolt/Physics/Character/CharacterBase.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CharacterVirtual.o: Jolt/Physics/Character/CharacterVirtual.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BroadPhase.o: Jolt/Physics/Collision/BroadPhase/BroadPhase.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BroadPhaseBruteForce.o: Jolt/Physics/Collision/BroadPhase/BroadPhaseBruteForce.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BroadPhaseQuadTree.o: Jolt/Physics/Collision/BroadPhase/BroadPhaseQuadTree.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/QuadTree.o: Jolt/Physics/Collision/BroadPhase/QuadTree.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CastConvexVsTriangles.o: Jolt/Physics/Collision/CastConvexVsTriangles.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CastSphereVsTriangles.o: Jolt/Physics/Collision/CastSphereVsTriangles.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CollideConvexVsTriangles.o: Jolt/Physics/Collision/CollideConvexVsTriangles.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CollideSphereVsTriangles.o: Jolt/Physics/Collision/CollideSphereVsTriangles.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CollisionDispatch.o: Jolt/Physics/Collision/CollisionDispatch.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CollisionGroup.o: Jolt/Physics/Collision/CollisionGroup.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EstimateCollisionResponse.o: Jolt/Physics/Collision/EstimateCollisionResponse.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GroupFilter.o: Jolt/Physics/Collision/GroupFilter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GroupFilterTable.o: Jolt/Physics/Collision/GroupFilterTable.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ManifoldBetweenTwoFaces.o: Jolt/Physics/Collision/ManifoldBetweenTwoFaces.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/NarrowPhaseQuery.o: Jolt/Physics/Collision/NarrowPhaseQuery.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/NarrowPhaseStats.o: Jolt/Physics/Collision/NarrowPhaseStats.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PhysicsMaterial.o: Jolt/Physics/Collision/PhysicsMaterial.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PhysicsMaterialSimple.o: Jolt/Physics/Collision/PhysicsMaterialSimple.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/BoxShape.o: Jolt/Physics/Collision/Shape/BoxShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CapsuleShape.o: Jolt/Physics/Collision/Shape/CapsuleShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CompoundShape.o: Jolt/Physics/Collision/Shape/CompoundShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ConvexHullShape.o: Jolt/Physics/Collision/Shape/ConvexHullShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ConvexShape.o: Jolt/Physics/Collision/Shape/ConvexShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/CylinderShape.o: Jolt/Physics/Collision/Shape/CylinderShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DecoratedShape.o: Jolt/Physics/Collision/Shape/DecoratedShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/EmptyShape.o: Jolt/Physics/Collision/Shape/EmptyShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/HeightFieldShape.o: Jolt/Physics/Collision/Shape/HeightFieldShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MeshShape.o: Jolt/Physics/Collision/Shape/MeshShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MutableCompoundShape.o: Jolt/Physics/Collision/Shape/MutableCompoundShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/OffsetCenterOfMassShape.o: Jolt/Physics/Collision/Shape/OffsetCenterOfMassShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PlaneShape.o: Jolt/Physics/Collision/Shape/PlaneShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RotatedTranslatedShape.o: Jolt/Physics/Collision/Shape/RotatedTranslatedShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ScaledShape.o: Jolt/Physics/Collision/Shape/ScaledShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Shape.o: Jolt/Physics/Collision/Shape/Shape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SphereShape.o: Jolt/Physics/Collision/Shape/SphereShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StaticCompoundShape.o: Jolt/Physics/Collision/Shape/StaticCompoundShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TaperedCapsuleShape.o: Jolt/Physics/Collision/Shape/TaperedCapsuleShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TaperedCylinderShape.o: Jolt/Physics/Collision/Shape/TaperedCylinderShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TriangleShape.o: Jolt/Physics/Collision/Shape/TriangleShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TransformedShape.o: Jolt/Physics/Collision/TransformedShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ConeConstraint.o: Jolt/Physics/Constraints/ConeConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Constraint.o: Jolt/Physics/Constraints/Constraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ConstraintManager.o: Jolt/Physics/Constraints/ConstraintManager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ContactConstraintManager.o: Jolt/Physics/Constraints/ContactConstraintManager.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DistanceConstraint.o: Jolt/Physics/Constraints/DistanceConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/FixedConstraint.o: Jolt/Physics/Constraints/FixedConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/GearConstraint.o: Jolt/Physics/Constraints/GearConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/HingeConstraint.o: Jolt/Physics/Constraints/HingeConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MotorSettings.o: Jolt/Physics/Constraints/MotorSettings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PathConstraint.o: Jolt/Physics/Constraints/PathConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PathConstraintPath.o: Jolt/Physics/Constraints/PathConstraintPath.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PathConstraintPathHermite.o: Jolt/Physics/Constraints/PathConstraintPathHermite.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PointConstraint.o: Jolt/Physics/Constraints/PointConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PulleyConstraint.o: Jolt/Physics/Constraints/PulleyConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RackAndPinionConstraint.o: Jolt/Physics/Constraints/RackAndPinionConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SixDOFConstraint.o: Jolt/Physics/Constraints/SixDOFConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SliderConstraint.o: Jolt/Physics/Constraints/SliderConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SpringSettings.o: Jolt/Physics/Constraints/SpringSettings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SwingTwistConstraint.o: Jolt/Physics/Constraints/SwingTwistConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TwoBodyConstraint.o: Jolt/Physics/Constraints/TwoBodyConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DeterminismLog.o: Jolt/Physics/DeterminismLog.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/IslandBuilder.o: Jolt/Physics/IslandBuilder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/LargeIslandSplitter.o: Jolt/Physics/LargeIslandSplitter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PhysicsScene.o: Jolt/Physics/PhysicsScene.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PhysicsSystem.o: Jolt/Physics/PhysicsSystem.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/PhysicsUpdateContext.o: Jolt/Physics/PhysicsUpdateContext.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Ragdoll.o: Jolt/Physics/Ragdoll/Ragdoll.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SoftBodyCreationSettings.o: Jolt/Physics/SoftBody/SoftBodyCreationSettings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SoftBodyMotionProperties.o: Jolt/Physics/SoftBody/SoftBodyMotionProperties.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SoftBodyShape.o: Jolt/Physics/SoftBody/SoftBodyShape.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SoftBodySharedSettings.o: Jolt/Physics/SoftBody/SoftBodySharedSettings.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/StateRecorderImpl.o: Jolt/Physics/StateRecorderImpl.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/MotorcycleController.o: Jolt/Physics/Vehicle/MotorcycleController.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TrackedVehicleController.o: Jolt/Physics/Vehicle/TrackedVehicleController.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VehicleAntiRollBar.o: Jolt/Physics/Vehicle/VehicleAntiRollBar.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VehicleCollisionTester.o: Jolt/Physics/Vehicle/VehicleCollisionTester.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VehicleConstraint.o: Jolt/Physics/Vehicle/VehicleConstraint.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VehicleController.o: Jolt/Physics/Vehicle/VehicleController.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VehicleDifferential.o: Jolt/Physics/Vehicle/VehicleDifferential.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VehicleEngine.o: Jolt/Physics/Vehicle/VehicleEngine.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VehicleTrack.o: Jolt/Physics/Vehicle/VehicleTrack.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/VehicleTransmission.o: Jolt/Physics/Vehicle/VehicleTransmission.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Wheel.o: Jolt/Physics/Vehicle/Wheel.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/WheeledVehicleController.o: Jolt/Physics/Vehicle/WheeledVehicleController.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/RegisterTypes.o: Jolt/RegisterTypes.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DebugRenderer.o: Jolt/Renderer/DebugRenderer.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DebugRendererPlayback.o: Jolt/Renderer/DebugRendererPlayback.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DebugRendererRecorder.o: Jolt/Renderer/DebugRendererRecorder.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/DebugRendererSimple.o: Jolt/Renderer/DebugRendererSimple.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkeletalAnimation.o: Jolt/Skeleton/SkeletalAnimation.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/Skeleton.o: Jolt/Skeleton/Skeleton.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkeletonMapper.o: Jolt/Skeleton/SkeletonMapper.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/SkeletonPose.o: Jolt/Skeleton/SkeletonPose.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TriangleSplitter.o: Jolt/TriangleSplitter/TriangleSplitter.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TriangleSplitterBinning.o: Jolt/TriangleSplitter/TriangleSplitterBinning.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/TriangleSplitterMean.o: Jolt/TriangleSplitter/TriangleSplitterMean.cpp
	@echo "$(notdir $<)"
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(PCH_PLACEHOLDER).d
endif